### ISSUE TITLE
不识码的求助

### ISSUE THREAD

**Issue by AnyWAT** [DrayChou/twitter-tools#1]
32位Windows 10PRO 1809/17763.55，官网下载的 python-2.7.15.msi 与 python-3.7.0.exe 都被系统阻止安装，唯有解压 python-3.7.0-embed-win32.zip 
在目录 block-zero-user 内 shift 右键启动 Poweshell，再运行 python，执行 pip3 install -r requirements.txt 报错如图，玩不下去了。。。
![image](https://user-images.githubusercontent.com/37962734/46896741-5a0af180-ceb1-11e8-831e-9cefc93c4fb8.png)
请大佬指下路😂谢谢！

**Comment by AnyWAT** [comment]
谢谢回复！不是Administrator 的管理员用户而已。按搜索到的方法成功安装 2.7.15 并更新神马，执行 pip3 install -r requirements.txt 同样报错。现折腾3.7.0的安装中。。。

**Comment by AnyWAT** [comment]
第一次执行 pip3 install -r requirements.txt 有下载进度。。。再执行结果：
![image](https://user-images.githubusercontent.com/37962734/47196821-20e0ee80-d395-11e8-9a85-2f17716bcfbc.png)
![image](https://user-images.githubusercontent.com/37962734/47196908-a5cc0800-d395-11e8-951d-21a00dd66b45.png)
![image](https://user-images.githubusercontent.com/37962734/47196949-d6ac3d00-d395-11e8-9b8d-830f4f6635cd.png)
请求大佬帮助😂

**Comment by DrayChou** [comment]
你现在已经跑起来了，但是你本地这台机器要能翻墙才能执行这个脚本。
因为到后面都是要直接请求 twitter 的地址。

**Comment by AnyWAT** [comment]
此前试了下XX-Net 的 X-Tunnel 1080（操作系统）全局代理，貌似不行，😁继续努力。。。
重点：下图的 Consumer key 与 Consumer secret 是什么？及末行没正常前的默认 n 正确？
![default](https://user-images.githubusercontent.com/37962734/47206615-aa0b1c00-d3bb-11e8-8994-536092f9df2e.png)

**Comment by DrayChou** [comment]
默认的是不对的，你要从之前你给的那个连接里那一对填进去

AnyWAT <notifications@github.com> 於 2018年10月19日 週五 下午4:29寫道：

**Comment by AnyWAT** [comment]
👍万分感谢！原来是系统安装 Python3.7 后XX-Net 托盘菜单不能修改操作系统代理设置，人工设置也未能正常运行。使用WuJie 代理后正常运行Block 中。。。怎么还有 Unblock ？
